name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Jack Henhapl
api-version: 1.13
main: edu.whimc.positiontracker.Tracker
commands:
  positiontracker:
    description: "Info for PositionTracker"