name: WHIMCPositionTracker
author: Jack Henhapl
main: edu.whimc.positiontracker.Tracker
version: ${project.version}
api-version: 1.13
description: Stores the positions of online players to a database.
commands:
  positiontracker:
    description: "Info for PositionTracker"